import {
    AccessibilityIcon,
    BabyCarry,
    BoltIcon,
    BuildingIcon,
    CatIcon,
    CrownIcon,
    DogIcon,
    EyeIcon,
    GlobeIcon,
    HeartIcon,
    HomeIcon,
    InjectionIcon,
    LeafIcon,
    MicroPhone,
    MoonIcon,
    RunningIcon,
    ShieldIcon,
    SofaIcon,
    StarIcon,
    UserIcon,
    UsersIcon,
    VolumeIcon,
    WalkIcon,
    WingsIcon,
    WrongIcon,
} from '@/components/svgs';
import type { TQuizStep } from '@/utils/types';

export const SMART_MATCH_STEPS: TQuizStep[] = [
    {
        id: 'activity',
        question: 'How active is your lifestyle?',
        hint: 'Pick the one that best fits your daily routine',
        type: 'single',
        layout: 'column',
        options: [
            {
                label: 'Homebody',
                description: 'I love staying in and relaxing',
                icon: SofaIcon,
                tags: ['Low maintenance', 'Apartment friendly', 'Lap cat/dog'],
            },
            {
                label: 'Moderately active',
                description: 'Daily walks and casual outings',
                icon: WalkIcon,
                tags: ['Apartment friendly'],
            },
            {
                label: 'Very active',
                description: 'Outdoor life, hikes and runs',
                icon: RunningIcon,
                tags: ['Active lifestyle', 'Needs outdoor space'],
            },
        ],
    },
    {
        id: 'household',
        question: "Who's in your home?",
        hint: 'Select all that apply',
        type: 'multi',
        layout: 'column',
        options: [
            {
                label: 'Young children',
                description: 'Kids under 10 in the house',
                icon: BabyCarry,
                tags: ['Good with kids'],
            },
            {
                label: 'Other dogs',
                description: 'I already have a dog',
                icon: DogIcon,
                tags: ['Good with dogs'],
            },
            {
                label: 'Cats',
                description: 'I already have a cat',
                icon: CatIcon,
                tags: ['Good with cats'],
            },
            {
                label: 'Just me or adults',
                description: 'No other pets or young children',
                icon: UserIcon,
                tags: ['Prefers to be only pet'],
            },
        ],
    },
    {
        id: 'personality',
        question: 'What personality are you looking for?',
        hint: 'Choose up to 3 traits you want in your pet',
        type: 'multi',
        maxSelections: 3,
        layout: 'tags',
        options: [
            { label: 'Playful', icon: GlobeIcon, tags: ['Playful'] },
            { label: 'Calm', icon: LeafIcon, tags: ['Calm'] },
            { label: 'Affectionate', icon: HeartIcon, tags: ['Affectionate'] },
            { label: 'Independent', icon: CrownIcon, tags: ['Independent'] },
            { label: 'Gentle', icon: WingsIcon, tags: ['Gentle'] },
            { label: 'Energetic', icon: BoltIcon, tags: ['Energetic'] },
            { label: 'Curious', icon: EyeIcon, tags: ['Curious'] },
            { label: 'Confident', icon: StarIcon, tags: ['Confident'] },
            { label: 'Shy & quiet', icon: MoonIcon, tags: ['Shy'] },
            { label: 'Vocal', icon: VolumeIcon, tags: ['Vocal'] },
        ],
    },
    {
        id: 'livingSpace',
        question: 'Where do you live?',
        hint: 'This helps us match pets suited to your space',
        type: 'single',
        layout: 'grid',
        options: [
            {
                label: 'Apartment',
                description: 'Flat or condo',
                icon: BuildingIcon,
                tags: ['Apartment friendly'],
            },
            {
                label: 'House with yard',
                description: 'Outdoor space available',
                icon: HomeIcon,
                tags: ['Needs outdoor space'],
            },
            {
                label: 'Small studio',
                description: 'Compact living space',
                icon: MicroPhone,
                tags: ['Apartment friendly', 'Low maintenance'],
            },
            {
                label: 'Shared home',
                description: 'Living with others',
                icon: UsersIcon,
                tags: [],
            },
        ],
    },
    {
        id: 'health',
        question: 'Any health or care preferences?',
        hint: 'Optional — skip if you have no preference',
        type: 'multi',
        layout: 'tags',
        options: [
            { label: 'Healthy', icon: HeartIcon, tags: ['Healthy'] },
            { label: 'Vaccinated', icon: InjectionIcon, tags: ['Vaccinated'] },
            { label: 'Neutered / Spayed', icon: WrongIcon, tags: ['Neutered / Spayed'] },
            { label: 'Dewormed', icon: ShieldIcon, tags: ['Dewormed'] },
            {
                label: 'Open to special needs',
                icon: AccessibilityIcon,
                tags: ['Needs Special Care', 'Disabled / Special Needs', 'Under Treatment'],
            },
        ],
    },
];

export const TOTAL_STEPS = SMART_MATCH_STEPS.length;