export const StaticRoutes = {
    PROFILE: '/profile',
    AUTH: '/auth',
    HOME: '/',
    BROWSE_PETS: '/browse-pets',
    LOST_FOUND: '/lost-found',
    MY_LISTING: '/my-listing',
    FAVOURITES: '/favourites',
    CONTACT_US: '/contact-us',
    ABOUT_US: '/about-us',
    TERMS_AND_CONDITIONS: '/terms-and-conditions',
    ADMIN: '/admin',
    REGISTER_ANIMAL: '/register-animal',
    REGISTRY: '/registry',
};